version: "3.7"

services:

  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hallo123
      - MYSQL_DATABASE=grapat
      - MYSQL_USER=grapat
      - MYSQL_PASSWORD=hallo123
  
  app:
    depends_on:
      - db
    build: ./app
    ports:
      - 80:8080
    volumes:
      #- ./app/target/grapat.war:/usr/local/tomcat/webapps/grapat.war
      - ./data:/usr/local/tomcat/webapps/grapat/data

volumes:
  data:


